apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: kumpraj/client
      context: client
      docker : 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src : 'src/**/*.js'
            dest : .
    - image: kumpraj/comments
      context: comments
      docker : 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src : '*.js'
            dest : .
    - image: kumpraj/event-bus
      context: event-bus
      docker : 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src : '*.js'
            dest : .
    - image: kumpraj/moderation
      context: moderation
      docker : 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src : '*.js'
            dest : .
    - image: kumpraj/posts
      context: posts
      docker : 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src : '*.js'
            dest : .
    - image: kumpraj/query
      context: query
      docker : 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src : '*.js'
            dest : .
          